[project]
name = "zoia-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "lxml>=5.4.0",
    "notebook>=7.4.2",
    "pandas>=2.2.3",
    "tiktoken>=0.9.0",
]
